import {shuffle} from './utils'

var japaneseExpressionList = [
  [ ['sa','yo', 'u','na', 'ra'], 'Goodbye' ],
  [ ['no','re', 'n'], 'Shop Curtain' ],
  [ ['ne','gi'], 'Onion' ],
  [ ['ho','ta', 'ru'], 'Firefly' ],
  [ ['ma', 'chi'], 'Town' ],
  [ ['ha', 'ga', 'ki'], 'Postcard' ],
  [ ['no', 'ko', 'gi', 'ri'], 'Saw(noun)' ],
  [ ['ya', 'sa', 'i'], 'Vegetable' ],
  [ ['yo','u', 'fu', 'ku'], 'Western Clothes' ],
  [ ['ru', 'tsu', 'bo'], 'Melting Pot' ],
  [ ['hi', 'ko', 'u', 'ki'], 'Airplane' ],
  [ ['ki', 'tsu', 'ne'], 'Fox' ],
  [ ['ki', 'mo', 'no'], 'Clothing' ],
  [ ['o', 'o', 'do', 'o', 'ri'], 'Main Street' ],
  [ ['se', 'n', 'se', 'i'], 'Teacher' ],
  [ ['chi', 'ka', 'ra'], 'Power' ],
  [ ['te', 'ga', 'mi'], 'Letter' ],
  [ ['sa', 'ka', 'na'], 'Fish' ],
  [ ['na', 'ma', 'e'], 'Name' ],
  [ ['wa', 'ka', 'ri', 'ma', 'se', 'n'], 'I don\'t understand' ],
  [ ['ya', 'me', 'te'], 'Stop it' ],
  [ ['te', 'a', 'ra', 'i'], 'Bathroom' ],
  [ ['ta', 'su', 'ke', 'te'], 'Help!' ],
  [ ['a', 'bu', 'na', 'i'], 'Dangerous' ],
  [ ['do', 'u', 'shi', 'ta'], 'What happened?' ],
  [ ['do', 'u', 'shi', 'te'], 'Why?' ],
  [ ['na', 'ni'], 'What?' ],
  [ ['da', 're'], 'Who' ],
  [ ['i', 'tsu'], 'When' ],
  [ ['do', 'ko'], 'Where' ],
  [ ['ta', 'be', 'ma', 'su'], 'To eat' ],
  [ ['ta', 'be', 'ma', 'se', 'n'], 'To not eat' ],
  [ ['no', 'mi', 'ma', 'su'], 'To drink' ],
  [ ['no', 'mi', 'ma', 'se', 'n'], 'To not drink' ],
  [ ['no', 'mi', 'mo', 'no'], 'A drink' ],
  [ ['ta', 'be', 'mo', 'no'], 'Food (noun)' ],
  //[ ['a', 'ri', 'ga', 'to', 'u', 'go', 'za', 'i','ma', 'su'], 'Thank you' ],
  //[ ['o', 'ha', 'yo', 'u', 'go', 'za', 'i', 'ma', 'su'], 'Good Morning' ],
  [ ['ko', 'n', 'ni', 'chi', 'wa'], 'Good Afternoon' ],
  [ ['ko', 'n', 'ba', 'n', 'wa'], 'Good Evening' ],
  [ ['de', 'wa', 'ma', 'ta'], 'See you later' ],
  [ ['ma', 'ta', 'a', 'shi', 'ta'], 'See you tomorrow' ],
  [ ['o', 'ya', 'su', 'mi', 'na', 'sa', 'i'], 'Good Night' ],
  [ ['su', 'mi', 'ma', 'se', 'n'], 'Excuse me' ],
  [ ['go', 'me', 'n', 'na', 'sa', 'i'], 'Sorry' ],
  [ ['a', 'ta', 'ra', 'shi', 'i'], 'New' ],
  [ ['o', 'o', 'ki', 'i'], 'Big' ],
  [ ['su', 'go', 'i'], 'Amazing' ],
  [ ['a', 'tsu', 'i'], 'Hot' ],
  [ ['sa', 'mu', 'i'], 'Cold' ]
];

export default function () {
  return shuffle (japaneseExpressionList).slice(0, 3);
}
